### PR TITLE
#3 Validations and Model Specs

### PR DESCRIPTION
**Pull request by Amtresu**
- [x] Add the following validations:
- [x] For the User model:
- [x] Name must not be blank.
- [x] PostsCounter must be an integer greater than or equal to zero.
- [x] For the Post model:
- [x] Title must not be blank.
- [x] Title must not exceed 250 characters.
- [x] CommentsCounter must be an integer greater than or equal to zero.
- [x] LikesCounter must be an integer greater than or equal to zero.
- [x] Add unit specs for all of your models' methods and validations.

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @Amtresu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses an old version of README, kindly consider using the new README template provided by microverse for more professional documentation of your work

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Amtresu** [comment]
@Ismailco Hello, I went ahead and resubmitted because I'm not really sure what you are referring to when you say my README is not up to par. I believe the README includes all the fields it should at this time. If you believe otherwise please give me some specifics. 
Cheers

**Comment by Ismailco** [comment]
@Amtresu, microverse updated the README template, you should use the [new template](https://github.com/microverseinc/readme-template)

Screenshot_20221124_235718

**Comment by Amtresu** [comment]
@Ismailco Thanks, in the future it would be helpful to include this in your reviews, as in my experience this information has not been officially announced. This is the first time I've seen or heard of this new template.

**Comment by prolajumokeoni** [comment]
Hi @Amtresu, this was officially announced on the announcement slack channel, the readme is now a requirement to get a review 👍🏿 good job adding it 👍🏿

**Review by prolajumokeoni — APPROVED** [review]
Hi @Amtresu 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
